### ISSUE TITLE
Eliminar `descripcion_lugar` de Orden

### ISSUE THREAD

**Issue by Galindo-lab** [servicio-profesional-uabc/prestamos-audiovisual-mexicali#105]
¿y si mejor ponemos que escriba toda la informacion en `descripcion`?

**Comment by DeysiRR** [comment]
Es que lo hicimos así porque nos estábamos basando en la hoja de control que ellos llevan

**Comment by Galindo-lab** [comment]
se ve un poco extraño en la interfaz, pero así lo voy a dejar 
![image](https://github.com/servicio-profesional-uabc/prestamos-audiovisual-mexicali/assets/78140218/21a253c7-fe11-4426-85f6-a9f1306abb07)
