### ISSUE TITLE
Agregar permisos de prestatario a un maestro no da la opcion de hacer solicitud

### ISSUE THREAD

**Issue by DiegoAndresGlez** [servicio-profesional-uabc/prestamos-audiovisual-mexicali#206]
![image](https://github.com/servicio-profesional-uabc/prestamos-audiovisual-mexicali/assets/57697717/f61f52ad-c65e-4cfd-b27b-bafe6cf7d9f7)

![image](https://github.com/servicio-profesional-uabc/prestamos-audiovisual-mexicali/assets/57697717/8f667512-a62e-42ba-b5d6-35968bf8ab43)

**Comment by Galindo-lab** [comment]
@DiegoAndresGlez esto ya esta arreglado en mi rama
