### ISSUE TITLE
Creación de ordenes sin nombre de producción

### ISSUE THREAD

**Issue by FranciscoJHOrnelas** [servicio-profesional-uabc/prestamos-audiovisual-mexicali#246]
Las ordenes se pueden generar con el campo de nombre de producción vacío, lo que puede generar errores en el admin y otros métodos.

![image](https://github.com/servicio-profesional-uabc/prestamos-audiovisual-mexicali/assets/111381373/3e646076-7858-46bb-87e6-f10dfce98d12)

**Comment by DiegoAndresGlez** [comment]
![image](https://github.com/servicio-profesional-uabc/prestamos-audiovisual-mexicali/assets/57697717/c6fd01c0-2ad3-4729-91b4-fb419cd1d727)
El form de Filtros lo hace obligatorio? Quiza te refieres crear ordenes desde /admin?

**Comment by Galindo-lab** [comment]
@DiegoAndresGlez esto se puede solucionar en los modelos agregando que el nombre no sea 'blank'
