### ISSUE TITLE
Ordenes pendientes al solicitar equipo

### ISSUE THREAD

**Issue by Galindo-lab** [servicio-profesional-uabc/prestamos-audiovisual-mexicali#54]
¿qué pasará con las ordenes que están esperando aprobaciones en el método Unidades?

**Comment by Galindo-lab** [comment]
@FranciscoJHOrnelas se te pasó agregar las ordenes que estan esperando autorización.

**Comment by Galindo-lab** [comment]
Vava, ¿agregaste las pruebas unitaras para ese caso?

**Comment by FranciscoJHOrnelas** [comment]
Sip

**Comment by Galindo-lab** [comment]
Vava
