### ISSUE TITLE
Solicitar al Usuario su correo al ingresar

### ISSUE THREAD

**Issue by Galindo-lab** [servicio-profesional-uabc/prestamos-audiovisual-mexicali#62]
como no tenemos el correo electrónico del usuario es necesario que lo ingrese en un form al iniciar

**Comment by Milkus002** [comment]
¿Quieres algo así como que se registre por primera vez? Que si él quiere iniciar sesión, pero no está registrado ni nada, ¿se le muestra o se le redirige al formulario? Y si es así, ¿cómo se le tomaría en cuenta como prestatario, o igual tiene que definir a qué tipo de usuario quiere registrarse?

**Comment by Galindo-lab** [comment]
Quizá podríamos bloquear que el usuario entre al menu hasta que ingrese su correo

**Comment by Galindo-lab** [comment]
ya se agrego la pantalla.
